apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pause-production

labels:
  - includeSelectors: true
    pairs:
      project: project-pause

resources:
  - deployment.yaml

images:
  - name: public.ecr.aws/eks-distro/kubernetes/pause
    newTag: "3.9"
