apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./project.yaml
  - ./pause-0
  - ./pause-1
  - ./pause-2
  - ./pause-3
  - ./pause-4
  - ./pause-5
  - ./pause-6
  - ./pause-7
  - ./pause-8
  - ./pause-9
