apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-production

labels:
  - includeSelectors: true
    pairs:
      project: project-nginx

resources:
  - deployment.yaml
  - serviceAccount.yaml
  - service.yaml

images:
  - name: public.ecr.aws/nginx/nginx
    newTag: 1.29.4-alpine
