apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pause-0
    project: project-pause
  name: pause-0
spec:
  replicas: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: pause-0
      project: project-pause
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/tags: '{"app":"app","component":"component","subcomponent":"subcomponent","environment":"environment","git.commit.sha":
                  "12596363b3de40b06f981fb85d82311e8c0ed512", "git.repository_url": "git.repository_url", "team":
                  "team", "businessunit": "businessunit"}'
      labels:
        app: pause-0
        project: project-pause
    spec:
      containers:
        - env:
            - name: ENVIRONMENT
              value: production
            - name: UUID
              value: "12596363b3de40b06f981fb85d82311e8c0ed511"
          image: public.ecr.aws/eks-distro/kubernetes/pause
          imagePullPolicy: IfNotPresent
          name: pause-0
